<?php
function inverse($x) {
    if (!$x) {
        throw new Exception('Division par zÃ©ro.');
    }
    return 1/$x;
}

try {
    echo inverse(1) . "\n";
} catch (Exception $e) {
    echo 'Exception reÃ§ue : ',  $e->getMessage(), "\n";
} finally { // NOK {{Avoid using try-catch-finally}}
    echo "PremiÃ¨re fin.\n";
}

try {
    echo inverse(2) . "\n";
} catch (Exception $e) {
    echo 'Exception reÃ§ue : ',  $e->getMessage(), "\n";
}

